cache_file: /path/to/cache_file
keep: 10 # articles to keep in cache
feeds:
  - user: "username-to-post-with"
    url: "https://api.zotero.org/[users or groups]/[your-user or group-id]/items/top"
    channel: "#channel-to-post-to"
    webhook: "https://hooks.slack.com/services/[an api key]"
  - user: "another-username-to-post-with"
    url: "https://api.zotero.org/[users or groups]/[your-user or group-id]/items/top"
    channel: "#another-channel-to-post-to"
    webhook: "https://hooks.slack.com/services/[a second api key]"
